# This is the configuration used to check the rubocop source code.

Documentation:
  Enabled: false

Rails:
    Enabled: true

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/initializers/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Style/ClassAndModuleChildren:
  EnforcedStyle: nested