language: ruby

rvm:
  - 2.4.0

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test;' -U postgres

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

test:
  adapter: postgresql
  database: travis_ci_test

addons:
  code_climate:
    repo_token: eaee36b742a18800a908b647a1b30fa0ac5679b92b3b104875557eba30325370

after_success:
  - bundle exec codeclimate-test-reporter